cmake_minimum_required(VERSION 3.21)
file(READ "${ROOT}/CoopPlugin/src/main.cpp" plugin)
file(READ "${ROOT}/runtime/session/redscript/CP2077Coop/natives.reds" declarations)
file(READ "${ROOT}/runtime/session/cet/CP2077Coop/init.lua" lua)
string(REGEX MATCHALL "CGlobalFunction::Create\\(\"CP2077Session_[A-Za-z]+\"" native_matches "${plugin}")
set(native_names)
foreach(entry IN LISTS native_matches)
    string(REGEX REPLACE ".*\"(CP2077Session_[A-Za-z]+)\"" "\\1" name "${entry}")
    list(APPEND native_names "${name}")
endforeach()
string(REGEX MATCHALL "public native func CP2077Session_[A-Za-z]+" reds_matches "${declarations}")
set(reds_names)
foreach(entry IN LISTS reds_matches)
    string(REPLACE "public native func " "" name "${entry}")
    list(APPEND reds_names "${name}")
endforeach()
list(SORT native_names)
list(SORT reds_names)
if(NOT native_names OR NOT "${native_names}" STREQUAL "${reds_names}")
    message(FATAL_ERROR "Plugin/REDscript native registration mismatch")
endif()
string(REGEX MATCHALL "Game\\.CP2077Session_[A-Za-z]+" calls "${lua}")
foreach(call IN LISTS calls)
    string(REPLACE "Game." "" name "${call}")
    if(NOT name IN_LIST native_names)
        message(FATAL_ERROR "CET calls undeclared native ${name}")
    endif()
endforeach()
foreach(source IN ITEMS plugin lua declarations)
    if("${${source}}" MATCHES "CP1|RP1|CP2077Coop_PushPlayerState|-666|-777|8888|9999")
        message(FATAL_ERROR "Legacy protocol leaked into typed bridge: ${source}")
    endif()
endforeach()
