set(asset "${ROOT}/runtime/session/assets/source/raw/base/cp2077coop/entities/CP2077Coop_NetworkHumanoid.ent.json")
file(READ "${asset}" json)
function(expect_json out)
    string(JSON value GET "${json}" ${ARGN})
    set(${out} "${value}" PARENT_SCOPE)
endfunction()
expect_json(container Data RootChunk "$type")
expect_json(root Data RootChunk entity Data "$type")
string(JSON component_count LENGTH "${json}" Data RootChunk components)
expect_json(component0 Data RootChunk components 0 "$type")
expect_json(component1 Data RootChunk components 1 "$type")
string(JSON chunk_count LENGTH "${json}" Data RootChunk compiledData Data Chunks)
expect_json(chunk0 Data RootChunk compiledData Data Chunks 0 "$type")
expect_json(anim_graph Data RootChunk compiledData Data Chunks 1 graph DepotPath "$value")
expect_json(anim_rig Data RootChunk compiledData Data Chunks 1 rig DepotPath "$value")
expect_json(mesh Data RootChunk compiledData Data Chunks 2 mesh DepotPath "$value")
expect_json(binding Data RootChunk compiledData Data Chunks 2 skinning Data "$type")
expect_json(binding_name Data RootChunk compiledData Data Chunks 2 skinning Data bindName "$value")
expect_json(parent_binding Data RootChunk compiledData Data Chunks 2 parentTransform Data "$type")
if(NOT container STREQUAL "entEntityTemplate" OR NOT root STREQUAL "entEntity")
    message(FATAL_ERROR "Prototype must be an entEntityTemplate with an entEntity root")
endif()
if(NOT component_count EQUAL 2 OR NOT component0 STREQUAL "entAnimatedComponent" OR NOT component1 STREQUAL "entSkinnedMeshComponent")
    message(FATAL_ERROR "Prototype component set is not the approved minimal pair")
endif()
if(NOT chunk_count EQUAL 3 OR NOT chunk0 STREQUAL "entEntity")
    message(FATAL_ERROR "Compiled template chunks do not match the minimal entity/component set")
endif()
if(NOT anim_rig STREQUAL "base\\characters\\base_entities\\woman_base\\woman_base.rig")
    message(FATAL_ERROR "Unexpected humanoid rig")
endif()
if(NOT anim_graph STREQUAL "base\\gameplay\\anim_graphs\\humanoid.animgraph")
    message(FATAL_ERROR "Unexpected animation graph")
endif()
if(NOT mesh STREQUAL "base\\characters\\appearances\\main_npc\\proxy\\judy_default\\judy_default.mesh")
    message(FATAL_ERROR "Unexpected visual test mesh")
endif()
if(NOT binding STREQUAL "entSkinningBinding" OR NOT binding_name STREQUAL "CP2077Coop_NetworkHumanoid" OR NOT parent_binding STREQUAL "entHardTransformBinding")
    message(FATAL_ERROR "Skinning/transform bindings do not resolve to the animated root")
endif()
foreach(forbidden NPCPuppet GameObject entAIControllerComponent entNavigationComponent entHitReactionComponent entDamageManagerComponent entRagdollComponent)
    string(FIND "${json}" "${forbidden}" found)
    if(NOT found EQUAL -1)
        message(FATAL_ERROR "Forbidden gameplay type in prototype: ${forbidden}")
    endif()
endforeach()
message(STATUS "Render-only prototype JSON structure validated; engine loading/rendering is unverified")