file(READ "${ROOT}/runtime/import-manifest.json" manifest)
string(JSON count LENGTH "${manifest}")
math(EXPR last "${count} - 1")
foreach(i RANGE ${last})
    string(JSON path GET "${manifest}" ${i} target)
    string(JSON expected GET "${manifest}" ${i} sha256)
    file(SHA256 "${ROOT}/${path}" actual)
    string(TOLOWER "${expected}" expected)
    if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "Imported baseline hash mismatch: ${path}")
    endif()
endforeach()
message(STATUS "All ${count} imported runtime hashes match")
