set(asset "${ROOT}/runtime/session/assets/source/raw/base/cp2077coop/entities/CP2077Coop_NetworkHumanoid.ent.json")
file(READ "${asset}" json)
function(expect_json out)
    string(JSON value GET "${json}" ${ARGN})
    set(${out} "${value}" PARENT_SCOPE)
endfunction()
expect_json(container Data RootChunk "$type")
expect_json(root Data RootChunk entity Data "$type")
string(JSON component_count LENGTH "${json}" Data RootChunk components)
expect_json(component0 Data RootChunk components 0 "$type")
expect_json(component1 Data RootChunk components 1 "$type")
string(JSON chunk_count LENGTH "${json}" Data RootChunk compiledData Data Chunks)
expect_json(chunk0 Data RootChunk compiledData Data Chunks 0 "$type")
expect_json(chunk1 Data RootChunk compiledData Data Chunks 1 "$type")
expect_json(chunk2 Data RootChunk compiledData Data Chunks 2 "$type")
expect_json(anim_graph Data RootChunk compiledData Data Chunks 1 graph DepotPath "$value")
expect_json(anim_rig Data RootChunk compiledData Data Chunks 1 rig DepotPath "$value")
expect_json(mesh Data RootChunk compiledData Data Chunks 2 mesh DepotPath "$value")
expect_json(binding Data RootChunk compiledData Data Chunks 2 skinning Data "$type")
expect_json(binding_name Data RootChunk compiledData Data Chunks 2 skinning Data bindName "$value")
expect_json(parent_binding Data RootChunk compiledData Data Chunks 2 parentTransform Data "$type")
if(NOT container STREQUAL "entEntityTemplate" OR NOT root STREQUAL "entEntity")
    message(FATAL_ERROR "Prototype must be an entEntityTemplate with an entEntity root")
endif()
if(NOT component_count EQUAL 2 OR NOT component0 STREQUAL "entAnimatedComponent" OR NOT component1 STREQUAL "entSkinnedMeshComponent")
    message(FATAL_ERROR "Prototype component set is not the approved minimal pair")
endif()
if(NOT chunk_count EQUAL 3 OR NOT chunk0 STREQUAL "entEntity" OR NOT chunk1 STREQUAL "entAnimatedComponent" OR NOT chunk2 STREQUAL "entSkinnedMeshComponent")
    message(FATAL_ERROR "Compiled template chunks do not match the minimal entity/component set")
endif()
if(NOT anim_rig STREQUAL "base\\characters\\base_entities\\woman_base\\woman_base.rig")
    message(FATAL_ERROR "Unexpected humanoid rig")
endif()
set(expected_graph "base\\cp2077coop\\animations\\networkhumanoid_idle.animgraph")
if(NOT anim_graph STREQUAL "${expected_graph}")
    message(FATAL_ERROR "Unexpected animation graph")
endif()
if(NOT mesh STREQUAL "base\\characters\\appearances\\main_npc\\proxy\\judy_default\\judy_default.mesh")
    message(FATAL_ERROR "Unexpected visual test mesh")
endif()
if(NOT binding STREQUAL "entSkinningBinding" OR NOT binding_name STREQUAL "CP2077Coop_NetworkHumanoid" OR NOT parent_binding STREQUAL "entHardTransformBinding")
    message(FATAL_ERROR "Skinning/transform bindings do not resolve to the animated root")
endif()
foreach(forbidden NPCPuppet GameObject entAIControllerComponent entNavigationComponent entHitReactionComponent entDamageManagerComponent entRagdollComponent)
    string(FIND "${json}" "${forbidden}" found)
    if(NOT found EQUAL -1)
        message(FATAL_ERROR "Forbidden gameplay type in prototype: ${forbidden}")
    endif()
endforeach()

# Template and compiled component must agree: the passive idle graph uses one
# installed animation set, with no controller or gameplay variable conditions.
function(check_animated_component)
    string(JSON component GET "${json}" ${ARGN})
    string(JSON graph GET "${component}" graph DepotPath "$value")
    string(JSON rig GET "${component}" rig DepotPath "$value")
    string(JSON controller TYPE "${component}" controlBinding)
    string(JSON set_count LENGTH "${component}" animations gameplay)
    string(JSON cinematic_count LENGTH "${component}" animations cinematics)
    if(NOT graph STREQUAL "${expected_graph}" OR NOT rig STREQUAL "${anim_rig}" OR NOT controller STREQUAL "NULL")
        message(FATAL_ERROR "Passive animated component has incompatible graph, rig or controller")
    endif()
    if(NOT set_count EQUAL 1 OR NOT cinematic_count EQUAL 0)
        message(FATAL_ERROR "Passive idle requires exactly one gameplay animation set and no cinematics")
    endif()
    string(JSON anim_set GET "${component}" animations gameplay 0 animSet DepotPath "$value")
    string(JSON variable_count LENGTH "${component}" animations gameplay 0 variableNames)
    if(NOT anim_set STREQUAL "base\\animations\\npc\\gameplay\\woman_average\\gang\\unarmed\\wa_gang_unarmed_locomotion_combat.anims" OR NOT variable_count EQUAL 0)
        message(FATAL_ERROR "Unexpected or conditional passive idle animation set")
    endif()
endfunction()
check_animated_component(Data RootChunk components 0)
check_animated_component(Data RootChunk compiledData Data Chunks 1)

file(READ "${ROOT}/runtime/session/assets/source/raw/base/cp2077coop/animations/networkhumanoid_idle.animgraph.json" graph_json)
function(check_graph_value expected)
    string(JSON actual GET "${graph_json}" ${ARGN})
    if(NOT actual STREQUAL "${expected}")
        message(FATAL_ERROR "Passive idle graph ${ARGN}: expected ${expected}, got ${actual}")
    endif()
endfunction()
function(check_graph_length expected)
    string(JSON actual LENGTH "${graph_json}" ${ARGN})
    if(NOT actual EQUAL expected)
        message(FATAL_ERROR "Passive idle graph ${ARGN}: expected ${expected} entries, got ${actual}")
    endif()
endfunction()
check_graph_value(animAnimGraph Data RootChunk "$type")
check_graph_length(0 Data EmbeddedFiles)
check_graph_length(0 Data RootChunk animFeatures)
check_graph_length(0 Data RootChunk additionalAnimDatabases)
check_graph_length(3 Data RootChunk nodesToInit)
check_graph_value(0 Data RootChunk rootNode HandleRefId)
check_graph_value(0 Data RootChunk nodesToInit 0 HandleId)
check_graph_value(1 Data RootChunk nodesToInit 1 HandleRefId)
check_graph_value(2 Data RootChunk nodesToInit 2 HandleRefId)
set(root_node Data RootChunk nodesToInit 0 Data)
set(output_node ${root_node} nodes 0 Data)
set(clip_node ${output_node} node node Data)
check_graph_value(animAnimNode_Root ${root_node} "$type")
check_graph_length(2 ${root_node} nodes)
check_graph_value(1 ${root_node} nodes 0 HandleId)
check_graph_value(2 ${root_node} nodes 1 HandleRefId)
check_graph_value(animAnimNode_Output ${output_node} "$type")
check_graph_value(2 ${output_node} node node HandleId)
check_graph_value(animAnimNode_SkAnim ${clip_node} "$type")
check_graph_value(idle_stand ${clip_node} animation "$value")
check_graph_value(1 ${clip_node} isLooped)
foreach(flag applyMotion collectEvents fireAnimLoopEvent)
    check_graph_value(0 ${clip_node} ${flag})
endforeach()
check_graph_value(1 Data RootChunk timeDeltaMultiplier)
foreach(flag isPaused useAnimCommands useAnimCommandsForCrowd useAnimStaticCommands)
    check_graph_value(0 Data RootChunk ${flag})
endforeach()
foreach(variables boolVariables floatVariables intVariables quaternionVariables transformVariables vectorVariables)
    check_graph_length(0 Data RootChunk variables Data ${variables})
endforeach()
message(STATUS "Passive entity and idle graph JSON contracts validated; animation playback requires separate live evidence")
