// Matched with the typed session plugin. Never install alongside legacy natives.reds.
public native func CP2077Session_SetActive(active: Bool) -> Void;
public native func CP2077Session_PushLocal(x: Float, y: Float, z: Float, yawRadians: Float) -> Void;
public native func CP2077Session_BeginFrame() -> Uint32;
public native func CP2077Session_Select(index: Uint32) -> Bool;
public native func CP2077Session_Bind(entity: Uint64, local: EntityID) -> Bool;
public native func CP2077Session_Phase() -> Uint32;
public native func CP2077Session_Generation() -> Uint64;
public native func CP2077Session_Host() -> Uint32;
public native func CP2077Session_Self() -> Uint32;
public native func CP2077Session_Session() -> Uint64;
public native func CP2077Session_Entity() -> Uint64;
public native func CP2077Session_Player() -> Uint32;
public native func CP2077Session_X() -> Float;
public native func CP2077Session_Y() -> Float;
public native func CP2077Session_Z() -> Float;
public native func CP2077Session_Yaw() -> Float;
public native func CP2077Session_SelfEntity() -> Uint64;
public native func CP2077Session_NpcOffer(local: EntityID, record: TweakDBID, x: Float, y: Float, z: Float, yawRadians: Float) -> Bool;
public native func CP2077Session_NpcForget(local: EntityID) -> Void;
public native func CP2077Session_NpcSelect(index: Uint32) -> Bool;
public native func CP2077Session_Unbind(entity: Uint64) -> Bool;
public native func CP2077Session_Resolve(local: EntityID) -> Uint64;
public native func CP2077Session_Epoch() -> Uint32;
public native func CP2077Session_NpcCapacity() -> Uint32;
public native func CP2077Session_BubbleRadius() -> Float;
public native func CP2077Session_NpcCount() -> Uint32;
public native func CP2077Session_NpcEntity() -> Uint64;
public native func CP2077Session_NpcRecord() -> TweakDBID;
public native func CP2077Session_NpcX() -> Float;
public native func CP2077Session_NpcY() -> Float;
public native func CP2077Session_NpcZ() -> Float;
public native func CP2077Session_NpcYaw() -> Float;
